name: "Auto merge"

permissions:
  pull-requests: write
  contents: write

on:
  workflow_call:
    inputs:
      pullRequestUrl:
        required: true
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  automerge:
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Dependabot metadata"
        id: "metadata"

        uses: "dependabot/fetch-metadata@v1.5.1"

        with:
          github-token: ${{ secrets.envPAT }}

      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          lfs: false
          persist-credentials: false

      - name: "print update-type"

        run: echo ${{ steps.metadata.outputs.update-type }}

      - name: "Enable auto-merge for Dependabot PRs"
        if: ${{steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch'}}

        run: gh pr merge --auto --merge "$PR_URL"

        env:
          PR_URL: "${{ inputs.pullRequestUrl }}"
          GITHUB_TOKEN: ${{ secrets.envPAT }}
